// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uopfbymmygvvljmevczf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvcGZieW1teWd2dmxqbWV2Y3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NDMwNDMsImV4cCI6MjA0OTQxOTA0M30.yEQdeJtSdg07EhxQGAeyeuTLQC0ELzpNLv7gzuvLlWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);